/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CommandIndexRouteImport } from './routes/command.index'
import { Route as CommandAnalyticsRouteImport } from './routes/command.analytics'
import { Route as CommandAppsRouteImport } from './routes/command.apps'
import { Route as CommandHiveRouteImport } from './routes/command.hive'
import { Route as CommandSettingsRouteImport } from './routes/command.settings'
import { Route as CommandThreatsRouteImport } from './routes/command.threats'
import { Route as CommandTimelineRouteImport } from './routes/command.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommandRoute,
} as any)
const CommandAnalyticsRoute = CommandAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CommandRoute,
} as any)
const CommandAppsRoute = CommandAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => CommandRoute,
} as any)
const CommandHiveRoute = CommandHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => CommandRoute,
} as any)
const CommandSettingsRoute = CommandSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CommandRoute,
} as any)
const CommandThreatsRoute = CommandThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => CommandRoute,
} as any)
const CommandTimelineRoute = CommandTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CommandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRouteWithChildren
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/apps': typeof CommandAppsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/timeline': typeof CommandTimelineRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/apps': typeof CommandAppsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/timeline': typeof CommandTimelineRoute
  '/command': typeof CommandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRouteWithChildren
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/apps': typeof CommandAppsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/settings': typeof CommandSettingsRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/timeline': typeof CommandTimelineRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/command/analytics'
    | '/command/apps'
    | '/command/hive'
    | '/command/settings'
    | '/command/threats'
    | '/command/timeline'
    | '/command/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command/analytics'
    | '/command/apps'
    | '/command/hive'
    | '/command/settings'
    | '/command/threats'
    | '/command/timeline'
    | '/command'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/command/analytics'
    | '/command/apps'
    | '/command/hive'
    | '/command/settings'
    | '/command/threats'
    | '/command/timeline'
    | '/command/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/analytics': {
      id: '/command/analytics'
      path: '/analytics'
      fullPath: '/command/analytics'
      preLoaderRoute: typeof CommandAnalyticsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/apps': {
      id: '/command/apps'
      path: '/apps'
      fullPath: '/command/apps'
      preLoaderRoute: typeof CommandAppsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/hive': {
      id: '/command/hive'
      path: '/hive'
      fullPath: '/command/hive'
      preLoaderRoute: typeof CommandHiveRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/settings': {
      id: '/command/settings'
      path: '/settings'
      fullPath: '/command/settings'
      preLoaderRoute: typeof CommandSettingsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/threats': {
      id: '/command/threats'
      path: '/threats'
      fullPath: '/command/threats'
      preLoaderRoute: typeof CommandThreatsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/timeline': {
      id: '/command/timeline'
      path: '/timeline'
      fullPath: '/command/timeline'
      preLoaderRoute: typeof CommandTimelineRouteImport
      parentRoute: typeof CommandRoute
    }
  }
}

interface CommandRouteChildren {
  CommandAnalyticsRoute: typeof CommandAnalyticsRoute
  CommandAppsRoute: typeof CommandAppsRoute
  CommandHiveRoute: typeof CommandHiveRoute
  CommandSettingsRoute: typeof CommandSettingsRoute
  CommandThreatsRoute: typeof CommandThreatsRoute
  CommandTimelineRoute: typeof CommandTimelineRoute
  CommandIndexRoute: typeof CommandIndexRoute
}

const CommandRouteChildren: CommandRouteChildren = {
  CommandAnalyticsRoute: CommandAnalyticsRoute,
  CommandAppsRoute: CommandAppsRoute,
  CommandHiveRoute: CommandHiveRoute,
  CommandSettingsRoute: CommandSettingsRoute,
  CommandThreatsRoute: CommandThreatsRoute,
  CommandTimelineRoute: CommandTimelineRoute,
  CommandIndexRoute: CommandIndexRoute,
}

const CommandRouteWithChildren =
  CommandRoute._addFileChildren(CommandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
