/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CommandIndexRouteImport } from './routes/command.index'
import { Route as CommandAnalyticsRouteImport } from './routes/command.analytics'
import { Route as CommandHiveRouteImport } from './routes/command.hive'
import { Route as CommandThreatsRouteImport } from './routes/command.threats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommandRoute,
} as any)
const CommandAnalyticsRoute = CommandAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CommandRoute,
} as any)
const CommandHiveRoute = CommandHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => CommandRoute,
} as any)
const CommandThreatsRoute = CommandThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => CommandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRouteWithChildren
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command': typeof CommandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRouteWithChildren
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/hive': typeof CommandHiveRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/': typeof CommandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/command/analytics'
    | '/command/hive'
    | '/command/threats'
    | '/command/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command/analytics'
    | '/command/hive'
    | '/command/threats'
    | '/command'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/command/analytics'
    | '/command/hive'
    | '/command/threats'
    | '/command/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/analytics': {
      id: '/command/analytics'
      path: '/analytics'
      fullPath: '/command/analytics'
      preLoaderRoute: typeof CommandAnalyticsRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/hive': {
      id: '/command/hive'
      path: '/hive'
      fullPath: '/command/hive'
      preLoaderRoute: typeof CommandHiveRouteImport
      parentRoute: typeof CommandRoute
    }
    '/command/threats': {
      id: '/command/threats'
      path: '/threats'
      fullPath: '/command/threats'
      preLoaderRoute: typeof CommandThreatsRouteImport
      parentRoute: typeof CommandRoute
    }
  }
}

interface CommandRouteChildren {
  CommandAnalyticsRoute: typeof CommandAnalyticsRoute
  CommandHiveRoute: typeof CommandHiveRoute
  CommandThreatsRoute: typeof CommandThreatsRoute
  CommandIndexRoute: typeof CommandIndexRoute
}

const CommandRouteChildren: CommandRouteChildren = {
  CommandAnalyticsRoute: CommandAnalyticsRoute,
  CommandHiveRoute: CommandHiveRoute,
  CommandThreatsRoute: CommandThreatsRoute,
  CommandIndexRoute: CommandIndexRoute,
}

const CommandRouteWithChildren =
  CommandRoute._addFileChildren(CommandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
